### ISSUE TITLE
Generate a PDF?

### ISSUE THREAD

**Issue by dufferzafar** [brandon-rhodes/python-patterns#7]
Since this is a Sphinx based project, this should be straightforward (hopefully)

Having a PDF linked on the main site itself would be nice.

**Comment by brandon-rhodes** [comment]
Alas — I just tried `make latexpdf` and, after a `sudo apt install latexmk` to install the tool it needs, I got a cascade of errors like:
```
! Package inputenc Error: Unicode character - (U+2212)
(inputenc)                not set up for use with LaTeX.
```
At the moment I am inclined to leave Python Patterns as a plain web site, especially since I am still working on it. Maybe I can revisit the idea of a PDF, and work through the problems with TeX, when the site is complete and has all the design patterns from the Gang of Four.

Is there a use case you have that the HTML is proving to be a poor fit for?

**Comment by dufferzafar** [comment]
> Is there a use case you have that the HTML is proving to be a poor fit for?

Um, nothing in particular, really.

I'm just used to PDFs for doing all "long-form" reading. I download PDFs, put them on my iPad and annotate as I read through (using an Apple Pencil.) 

And when something like this happens (and I can't get a nice looking PDF) then I just make use of the Browser's Print to PDF functionality. So that is what I'll go with for now!

> work through the problems with TeX, when the site is complete and has all the design patterns from the Gang of Four.

I think, it'll be harder then, because there'll be LOTS of issues to fix.

**Comment by brandon-rhodes** [comment]
True, but I'll then be able to tackle the issues all at once :)

I'm going to close this for now, but once the site is completely I'll definitely pivot to the question of a printable format. Thanks for the idea!
